fragment ProductInfo on ProductC {
  productId
  productName
  productReference
  items {
    images {
      imageUrl
    }
    itemId
    name
    nameComplete
    complementName
    referenceId {
      Key
      Value
    }
  }
}
