#import './ProductInfoFragment.gql'

query SearchCollectionSkus(
  $ids: [Int],
) @context(provider: "vtex.collections") {
  products: getProductsBySku(
    ids: $ids,
    from: 0,
    to: 9,
  ) {
    items {
      ...ProductInfo
    }
  }
}
